spring:
  datasource:
    url: jdbc:mysql://localhost:3306/loadtest
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  data:
    redis:
      host: redis
      port: 6379

server:
  port: 8080