spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/loadtest
#    username: root
#    password: 1234
  datasource:
    url: jdbc:h2:file:./data/demo-db;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE   # 프로젝트 내부에 H2 DB 저장, 동시 접속 가능
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000